### ISSUE TITLE
Convert IJM 15(2)

### ISSUE THREAD

**Issue by pbronka** [microsimulation/ijm#152]
Hi @gnott ,

Could you please convert IJM Issue 15(2) for us? 

These are the articles ijm.00260 - ijm.00265 in the S3 bucket.

Thank you!

**Comment by gnott** [comment]
Hi @pbronka, I downloaded them and generated output. In checking them for validity I noticed some things which cause exceptions to be raised, and some other things I noticed.

All articles have `<day>25</day><month>10</month>`, and I think they may need to have the date tags `<day>31</day><month>08</month>` to match the previous convention for a Summer issue.

On four articles there are specific validation messages:

`00260` is missing these tags `<volume>15</volume><issue>2</issue>`

`00261`, the parser does not find the Appendix title, I think if it is changed to be more like this it will work better:

```xml
<app id="A1">
<title>Appendix 1</title>
<sec id="s8"> 
```

`00263` 
- citation id `bib25` is missing a title
- its Appendix title tag can be moved like in article `00261`

`00264` 
- the Appendix 1 title tag can also be moved like in article `00261`
- the `<app id="A2">` is missing a title, and I wonder if this is actually supposed to be part of Appendix 1 ?
- its not causing errors, but I noticed `<sec id="s7">` the `@id` attribute is used seven times, when an `@id` attribute in XML would normally unique for every tag

I hope these are helpful notes to please modify the XML and to resupply them to the bucket.

The PDF and image file names looked good on these as far as I could see.

Thanks!

**Comment by pbronka** [comment]
Sorry about that, should be fixed now. Could you please try again? Thanks!

**Comment by gnott** [comment]
Much better results, thanks for these. It's good enough I'll create a PR containing the content for review.

The two footnotes in article `00264` caused an error when generating JSON output due to there is no `<label>` in the `<fn>` tag for these. For now, I used the `@id` attribute as the title because a title is required by the schema. It looks like this on the web page:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1779115/199850148-42095806-261a-4035-8fd2-54cc8bca0a1b.png">

If you want to add a `<label>` to the XML and you resupply a zip file for that article, I can change the article, either in the open PR or in a second PR after you merge the first one.

**Comment by pbronka** [comment]
Thanks a lot @gnott. Footnotes are simply numbered, so to save some time I changed the titles from BFN1 and BFN2 to 1. and 2. in the open PR, hope that's ok. I will still ask for the original XML to be fixed and reuploaded to the S3 bucket, but don't think this article will have to be converted again?

**Comment by gnott** [comment]
It would be the expected output and sounds fine to me, thanks @pbronka.

**Comment by pbronka** [comment]
Great, the merge appears to have been successful so I'll close this issue. Thanks again for converting this for us!
