### ISSUE TITLE
Convert IJM 15(3)

### ISSUE THREAD

**Issue by pbronka** [microsimulation/ijm#158]
Hi @gnott,

Could you please convert IJM 15(3) for us? Articles included in this issue are: 

ijm-00266.zip | zip | January 13, 2023, 18:45:56 (UTC+00:00) | 115.5 KB | Standard
ijm-00267.zip | zip | January 13, 2023, 18:45:55 (UTC+00:00) | 9.2 MB | Standard
ijm-00268.zip | zip | January 13, 2023, 18:45:50 (UTC+00:00) | 15.8 MB | Standard
ijm-00269.zip | zip | January 17, 2023, 08:11:00 (UTC+00:00) | 768.8 KB | Standard
ijm-00270.zip | zip | January 17, 2023, 08:12:53 (UTC+00:00) | 20.7 MB | Standard
ijm-00271.zip | zip | January 17, 2023, 08:10:59 (UTC+00:00) | 2.0 MB | Standard

Thank you!

**Comment by gnott** [comment]
I tried to generate output for these, and there are some minor validation issues with four of the articles, described below.

`00268`
citation id `bib30` has no uri value generated which is required for a web citation

00269
citation id `bib13` has no uri value (there looks like something in the `<source>` tag, but the parser puts it into the `website` attribute and not as the `uri`)

`00270`
The appendix section ends up having no `title`, this could be fixed by removing `<sec id="s9">` in the `<app>` tag and then the content is valid

(see Table A1 in Appendix A).

`00271`
similar to the appendix issue described for article 00270, if the `<sec id="s8">` is removed then the appendix content is valid.

A formatting note: the XML files in this batch were not pretty printed format, i.e. do not have any newline characters; it makes it harder to view them for problem diagnosis, however there's no bug or compatibility issue to have XML content which is all on one line.

If you would please consider these feedback about the four articles @pbronka, and if they are resupplied to the bucket I can generate output from them again.

**Comment by pbronka** [comment]
Thank you, these should be fixed now and have been re-uploaded to the S3 bucket.

**Comment by gnott** [comment]
These look really good and no problems generating output, here's a PR for your review https://github.com/microsimulation/ijm/pull/159
