### ISSUE TITLE
Convert articles for issue 17(1)

### ISSUE THREAD

**Issue by pbronka** [microsimulation/ijm#209]
Hi @gnott ,

Could you please convert articles ijm.00301 - ijm.00306 for us? 

(As you will notice, there is a gap in the DOIs. Articles 301 - 306 are a part of the 17(1) Spring Issue, and articles 291 - 300 will constitute a summer issue 17(2). Hope that's not a problem). 

Thanks!

**Comment by gnott** [comment]
Hi @pbronka, thanks for sending these through. To have articles in non-numeric order should work fine.

There were just a couple of these I had to modify the XML in order to produce valid JSON for the appendix data, in articles `00302` and `00306`. For each one, it worked well if I deleted the `<sec>` tag in the `<app-group>`. For example, to change

```xml
<app-group>
<app id="A1">
<sec id="s8">
<title>Appendix A</title>
```

to 

```xml
<app-group>
<app id="A1">
<title>Appendix A</title>
```

(and to remove the `</sec>` close tag naturally) was able to produce valid and visually correct output.

I noticed too inside the `ijm-00306.zip` file there's what looks like an extra `ijm-00305.zip` file, which could be removed, I can ignore it though.

I'm tempted to commit the output I created for now from the modified appendix XML, anticipating you agree to the changes I suggest above; I won't need to convert them again, unless you go with an alternate solution.

**Comment by pbronka** [comment]
Thanks a lot @gnott. I spotted some minor issues post-publication (page numbering restarting at 1, some typos in licence statement) but I should be able to fix them myself when I receive corrected PDFs from the typesetters.

**Comment by gnott** [comment]
Sounds great @pbronka, I'm glad to see these files were useful in the first round!

**Comment by pbronka** [comment]
Hi @gnott, I spotted some additional issues that have now been fixed and files uploaded to the S3 bucket. Sorry but would it be possible to convert these articles again?

**Comment by gnott** [comment]
Yes, the output was all valid according to the schema rules. Updated JSON and PDF files in PR https://github.com/microsimulation/ijm/pull/211

The diff for `00302.json` is showing some author affiliation values also changed, possibly for the better, but I'm not sure about the `Gawlay` value on one of them - something for you to review please.

**Comment by pbronka** [comment]
Thank you for spotting this, should be Galway of course - fixed now.
