### ISSUE TITLE
Convert special issue 17(2) summer 2024

### ISSUE THREAD

**Issue by pbronka** [microsimulation/ijm#215]
Hi @gnott ,

Could you please convert the following articles for us? These are a part of the (delayed) Summer 2024 Special Issue. 

- ijm-00307 (Editorial)
- ijm-00291
- ijm-00292
- ijm-00293
- ijm-00294
- ijm-00295
- ijm-00296
- ijm-00297
- ijm-00298
- ijm-00299
- ijm-00300

Please let me know if I could be of any assistance. 

Thanks!

**Comment by gnott** [comment]
Hi @pbronka,

I'm happy to convert these, and I have some results.

All of the articles have a publication date of December 2, 2024; would it be more accurate to have the date of August 31, 2024?

There are four articles with some schema validation failures, and suggestions to fix them follow.

## ijm-00298.xml

- [ ] reference id `bib102` is type `report`, and it will be valid if in  `<publisher-name>IUI Research Report No.1</publisher-name>` the `<publisher-name>` tag is changed to a `<source>` tag
- [ ] reference id `bib107`, similar to above,  change `<publisher-name>TRITA Research report, KTH, Stockholm</publisher-name>` to use a `<source>` tag

##  ijm-00292.xml

- [ ] reference id `bib16`, change `<publisher-name>Economic Research Reports, Federation of Swedish Industries</publisher-name>` to use a `<source>` tag
- [ ] reference id `bib17`, change `<publisher-name>Federation of Swedish Industries</publisher-name>` to use a `<source>` tag

##  ijm-00297.xml

In the appendix, by removing a (presumably surplus) `<sec>` tag the JSON output will be valid.

I suggest to change from

```xml
<app id="A1">
<sec id="s6">
<title>Appendix A</title>
```

to

```xml
<app id="A1">
<title>Appendix A</title>
```

(and remove the matching `</sec>` tag)

##  ijm-00298.xml

Similar to above, the first appendix change, from

```xml
<app id="A1">
<sec id="s10">
<title>Appendix A</title>
```

to

```xml
<app id="A1">
<title>Appendix A</title>
```

Then, there's a slightly tricky one. What remains includes

```xml
<sec id="s10-1">
<title>by Erol Taymaz</title>
</sec>
```

This will not produce valid JSON because the `<sec>` doesn't include a `<p>` tag. You may consider to use a `<p>` tag instead of `<sec>`, so the appendix looks like the following

```xml
<app id="A1">
<title>Appendix A</title>
<p>by Erol Taymaz</p>
<sec id="s10-2">
...
```

------

Please add your feedback or a note for when new zip files are available, and I'll convert them again.

**Comment by pbronka** [comment]
Hi @gnott , 

Thank you for that, that's very helpful. These files have now been fixed and re-uploaded.

**Comment by gnott** [comment]
Thanks for sending these @pbronka.

I modifed the publication dates in the others (which were not refreshed).

When looking at the appendix in article `00298` there were some anchor tag links across whole or multiple paragraphs. In the XML I noticed what looked like some duplicate `<xref>` tags, and after adjusting these, the links look better. I may not have it perfectly, and I can upload the XML here if it helps to get it right.

An example of how `00298` looked before editing:

![image](https://github.com/user-attachments/assets/b1926525-c543-43d1-bbc9-6ca7fd286147)

**Comment by pbronka** [comment]
Hi @gnott , thanks. Can I just clarify the publication date - for this issue, we would like to use the current date (or the 2nd of December) as the publication date, and not the 31st of August. Is this possible? I believe in json files it is currently set to the 31/08/2024? 

I can also see that the automatic checks are failing but this is a problem with the website. Do you know if/how we can deploy manually skipping these checks? 

Thank you.

**Comment by gnott** [comment]
My mistake, I didn't read your comment here very closely, and the new XML had August 31st dates, I jumped to the wrong conclusion. I've updated the `.json` files in the branch used for the PR https://github.com/microsimulation/ijm/pull/216 if that helps. Does the issue date remain as August 31st, 2024?

Also correct, `ijm-00291.xml` was the file name for the first in my feedback notes.

I'm not too sure about the automated pipeline results because I've not looked at them before.

Thanks!

**Comment by pbronka** [comment]
Thank you. Ideally we would set the issue date to the 2nd of December too. Unless that causes some problems for how the website / issues are structured. 

I will try to resolve the tests / pipeline issues.

**Comment by gnott** [comment]
I tried using actions/upload-artifact@v4 in the `.github/workflows/smoke.yml` file too on my test branch with the same result, although it still seems to run actions/upload-artifact@v2 regardless.

**Comment by pbronka** [comment]
Thank you for trying. I managed to publish this - the main pipeline seems to work. I will close this issue then. Thank you for your help with this as always, much appreciated.
