### ISSUE TITLE
Investigated n/a returned (n/a in json, need to check xml -> json)

### ISSUE THREAD

**Issue by hdrury1** [microsimulation/ijm#25]
@gnott to investigate

`eLocationID` Value was required to be valid. What should this value be?

**Comment by gnott** [comment]
In the JSON files it looks to be correct what I was suspecting, e.g.

`    "elocationId": "n/a",`

I added this value because and `elocationid` is required for schema validation.

In the XML files I have, there's no elocationid value to be used. Perhaps @FAtherden-eLife would know if these articles have an elocationid now?

If the articles do have an elocationid, we could update the `n/a` value in the JSON files to the appropriate value. Otherwise, I would need to convert all articles from the latest XML (which has elocationid data inside).

**Comment by FAtherden-eLife** [comment]
Thanks @gnott, yeah, I realise now what I said in the call was wrong. IJM don't have elocation-ids, since their content has page numbers instead. This must be why you used `n/a` instead, and makes total sense now why they were not present in the XML.

The equivalent citations details can be found in `article-meta` in the XML.
```xml
<article-meta>
...
<volume>12</volume>
<issue>1</issue>
<fpage>105</fpage>
<lpage>123</lpage>
...
</article-meta>
```

A workaround could be to concatenate the `fpage` and `lpage`, with a hyphen and use that as an elocation-id when generating the JSON, so that, for example, the citation details are here:
<img width="1146" alt="Screenshot 2020-07-08 at 17 08 52" src="https://user-images.githubusercontent.com/43879983/86943098-e6f1e600-c13d-11ea-8720-c39dad4038dd.png">

are 'CITE AS: IJM 2019;12:105-123'

But this, of course, wouldn't be semantically correct and might cause issues if the elocation-id is depended on elsewhere (for example if generating a BibTeX or RIS citation file).

I'm also unsure of IJM expectations as to what should display there, whether it would also include the issue number (which I think is pretty standard - eLife doesn't have those either). Perhaps @hdrury1 or @BlueReZZ would know?

I imagine the alternative (to that workaround) is changing the JSON Schema so that page range OR elocation-id was allowed, and changing the `bot-lax-adaptor` so that information is pulled out.

**Comment by gnott** [comment]
You've reminded me too that I inserted the "issue" value for IJM articles, which is not defined in the eLife RAML schema if I remember correctly.

Here are the lines in the `ijm` branch of `bot-lax-adaptor` I used to generate the IJM JSON (https://github.com/elifesciences/bot-lax-adaptor/blob/ijm/src/main.py#L591-L592)

```
    ('issue', [jats('issue'), to_int]),
    ('elocationId', [jats('elocation_id'), 'n/a']),
```

It is where I added `issue` and set a default for `elocationid`.

The most important part is probably to display the "CITE AS" to be an appropriate value for citing an article. The data is probably temporary and the RAML schema may be not used later when PRC happens? That's beyond what I know at this time.

**Comment by BlueReZZ** [comment]
Yes that's right. Complying with eLife API RAML is less important than the citation data being correct for the 'CITE AS' on the IJM site.

We will be editing the parts of the app that generate the BIB and RIS files under #21 so we can handle any idiosyncrasies around the semantics so a fix to concatenate the page numbers into the elocation could work for now.

We'll check in with IJM too.

**Comment by BlueReZZ** [comment]
It seems the standard way to provide a citation for the field of economics has a bit more than just the journal name and volume/pages so we're going to handle this in the code under https://github.com/microsimulation/ijm/issues/51

All the information we need should be available so it may be more accurate/correct to leave `elocationId` as `n/a` for now.

**Comment by BlueReZZ** [comment]
Having looked at the information we need, and given Matteo at IJM a preview of the new citation, it seems that the change to map `fpage` and `lpage` into the `elocationId` in the JSON would work really well for us. Given this is just for the purposes of display (and export as BIB/RIS etc) I think it's okay to pass it through that way.

**Comment by gnott** [comment]
In order to include the `fpage` and `lpage` values of the article itself in the JSON files, I will do a little enhancement of the XML parser and the JSON generator code. I'll regenerate from all the XML files I have on hand. This shoudl result in two lines added to each article JSON file in the repo, if I did it right, since all the other content will be (should be) unchanged.

**Comment by gnott** [comment]
If the article has no `fpage` or `lpage` value, the JSON will have a string of `n/a` for those values.
