### ISSUE TITLE
Code fix for reference date and author validation

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm#5]
Testing with some early sample content, data in the references sometimes cause validation errors in the demo project. I think this might be related to how the demo project is validating all the content against the eLife XML schema which is very strict.

In order to produce a working demo site in a timely manner, I investigated where in the code the exceptions are raised.

The first part is in the validation of the JSON data itself. To me it looks like the eLife API SDK libraries are imported and are out of scope to change these for the demo project. As such, I can add dummy values to the JSON to allow the demo site to accept it.

The end result of displaying the article on the web pages can be modified since it is part of the demo project itself.

I have some fairly simple code changes in order to account for the placeholder `date` and `authors` attributes for references that are missing these values. To assist in my process of converting XML to JSON to IJM demo site JSON, this is what I've arrived at:

- if `date` is missing, set it to `1000` (which is valid), then when formatting content for the web, any year of `1000` or less is omitted from display
- if `authors` is missing, set it to a group author with name of `n/a`, and that will also be omitted from display on the web page

There is still some work and decisions to be made about how the Google Scholar link will be populated when the year and author name data is not available.

## Subtasks

- [x] Add placeholder values to the JSON output when converting IJM XML to JSON
- [x] Commit drafted code changes to the demo project for placeholder `date` and `authors` values in references

## Assumptions and notes
- We could use this technology
- More notes or suggestions

@Melissa37 @BlueReZZ  I'm creating this issue to describe the method I've arrived at and to remember this workaround will be in place until an alternate solution can be invented.

**Comment by Melissa37** [comment]
@gnott I guess if that is the most efficient method to get the demo site up and running. It's interesting finding the issues in the XML.

My concern is that these will not be factored in for the final version. @thewilkybarkid needs to keep an eye on this for the building on final Libero.
Regarding references specifically, we always knew the eLife reference schema was very strict and few publishers would have the capacity to put the effort into getting their content to that quality. Its interesting seeing some of the dates issues - I think it's a filed-specific thing - it makes sense why some of the dates are ranges or unspecified. Some could be converted to date-in-citation in future (getting the author to provide the date s/he accessed the site, but again I don't think Mattero and his team have the capacity to police that.

Where possible, I am feeding back to them to get XML fixes, but because it is archive data they cannot do some.

Thanks @gnott !
