### ISSUE TITLE
Mendeley Open citation functionality proper work

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#60]
Check if Mendeley open citation functionalities work properly and generate respective reference.

**Comment by astrajescu** [comment]
Questions:
1. How do we check/test if the open citations (Mendeley, ReadCube and Papers) work properly? Moreover it looks like ReadCube is already obsolete as it has been integrated into Papers App - need to investigate.
2. When I access the ReadCube link on eLife magazine it opens the file in a different format, while on IJM site it opens the PDF version.
3. When I access the Papers link eiather on eLife or IJM it loads a blank page.

**Comment by olegderid** [comment]
**1. CLARIFIED - Mendeley download:**
1.1. register free account on https://www.mendeley.com/ site & login to Mendeley site
1.2. navigate to a specific article (e.g. http://microsimulation.pub/articles/00204)
1.3. hit the download button in the top right corner
1.4. hit the "Mendeley" link from the "Open Citations" section
      - Mendeley site is opened with the same named article
1.5. hit "Import" button
1.6. hit Library link
      - article with exact name & citation is disaplayed in Mendeley Library list

![mendeley_citation](https://user-images.githubusercontent.com/272698/88919826-72a9ee80-d274-11ea-9438-0a875a8acb9a.gif)

The above mentioned scenario could be automated, however need to make sure the Mendeley credentials are not stored as part of test artifact (due mendeley account hijack vulnerability), but as part of the CI environment variable.

CC: @gaenache , @astrajescu, @rtudvasev , @BlueReZZ

**Comment by olegderid** [comment]
**2. CLARIFICATION REQUIRED - Readcube download:**
Readcube has acquired Papers application, @astrajescu , please, confirm if this functionality is still in scope after acquisition?

**3. CLARIFICATION REQUIRED - Papers download;**
There is a mail thread open with the Papers App support regarding integration with the Browser extension. 

CC: @astrajescu, @BlueReZZ, @gaenache 
At this point the Readcube & Papers is assumed to be out of test scope in order to minimize CI workflow execution time. @astrajescu, @BlueReZZ , please, reply if this assumption is negative?

**Comment by astrajescu** [comment]
ReadCube and Papers will be implemented at a later phase.
